Jazzy add icon #18
sukhbirsekhon/FinanceTracker pull request #59
Opened 2021-05-08 02:18 UTC by Singh2je

## Proposed Changes
- Created 2 different views for the Home Fragment - homePageView and popUpTransactionView
- On click of the Add button, it makes the Transaction view visible, and when save button is clicked, it makes the homePageView Visible.

## Additional Info

## Checklist
- [ ] You have added unit tests
- [ ] You've added documentation
- [ ] You've assigned reviewers 
- [ ] You've assigned assignees 
- [ ] Your code builds clean without any errors or warnings
- [ ] You are following coding conventions

## Screenshots

2021-05-11 19:42 UTC, sukhbirsekhon requested changes
I added two comments. Please fix them and I'll merge your PR

2021-05-11 19:42 UTC, sukhbirsekhon commented on .idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
Do we really need this?

2021-05-16 02:06 UTC, Singh2je commented on app/src/main/java/home/project/group/financetracker/ui/home/HomeFragment.java
> +
Removed extra spaces and comments

2021-05-16 02:06 UTC, Singh2je commented on .idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
I removed it and it works fine.

2021-05-16 02:11 UTC, merged